# Generated by Django 4.1.4 on 2023-09-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="shortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_url", models.CharField(max_length=100)),
                ("og_url", models.URLField(max_length=700)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
